site_name: python-anvil
site_description: Anvil API
site_author: Allan Almazan

repo_url: https://github.com/anvilco/python-anvil
edit_uri: https://github.com/anvilco/python-anvil/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - API Usage: api_usage.md
  - CLI Usage: cli_usage.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
    - Credits: about/credits.md
